import {
  LogOut,
  User,
  Loader,
  Trash,
  Slash,
  Pen,
  CirclePlus,
  Newspaper,
  Settings,
  MessageSquareText,
  LayoutDashboard,
  X,
  Eye,
  CircleOff,
  type LucideIcon,
} from 'lucide-react';

export const Icons: Record<string, LucideIcon> = {
  logout: LogOut,
  loader: Loader,
  trash: Trash,
  user: User,
  slash: Slash,
  settings: Settings,
  plus: CirclePlus,
  pen: Pen,
  dashboard: LayoutDashboard,
  newspaper: Newspaper,
  commenting: MessageSquareText,
  delete: X,
  view: Eye,
  empty: CircleOff,
};
