import {
  Linkedin,
  LogOut,
  User,
  Menu,
  Info,
  Book,
  Loader,
  Trash,
  Crop,
  RotateCw,
  RotateCcw,
  FlipHorizontal,
  FlipVertical,
  ZoomIn,
  ZoomOut,
  Download,
  Upload,
  CircleX,
  CircleCheckBig,
  SkipForward,
  CircleArrowRight,
  CircleArrowLeft,
  HelpCircle,
  Diff,
  Eye,
  Move,
  Pen,
  Brush,
  Eraser,
  CirclePlus,
  CircleMinus,
  type LucideIcon,
} from 'lucide-react';

export const Icons: Record<string, LucideIcon> = {
  linkedin: Linkedin,
  logout: LogOut,
  user: User,
  menu: Menu,
  info: Info,
  book: Book,
  loader: Loader,
  trash: Trash,
  crop: Crop,
  rotateRight: RotateCw,
  rotateLeft: RotateCcw,
  flipHorizontal: FlipHorizontal,
  flipVertical: FlipVertical,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  download: Download,
  upload: Upload,
  cancel: CircleX,
  confirm: CircleCheckBig,
  skipForward: SkipForward,
  back: CircleArrowLeft,
  next: CircleArrowRight,
  helpCircle: HelpCircle,
  compare: Diff,
  preview: Eye,
  move: Move,
  draw: Brush,
  pen: Pen,
  eraser: Eraser,
  plus: CirclePlus,
  minus: CircleMinus,
};
